### ISSUE TITLE
Must specify a region

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [MantisAI/bell#3]
Just installed on an ec2 instance and received the following:

```
ubuntu@ip-XXX-XX-XX-XXX:~$ pip install pip install git+https://github.com/MantisAI/bell.git
ubuntu@ip-XXX-XX-XX-XXX:~$ bell https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/bell", line 8, in <module>
    sys.exit(app())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/ubuntu/.local/lib/python3.8/site-packages/bell.py", line 15, in bell
    ec2 = boto3.client("ec2")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/session.py", line 884, in create_client
    client = client_creator.create_client(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/client.py", line 102, in create_client
    client_args = self._get_client_args(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/client.py", line 384, in _get_client_args
    return args_creator.get_client_args(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/args.py", line 71, in get_client_args
    final_args = self.compute_client_args(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/args.py", line 148, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/args.py", line 234, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/args.py", line 320, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/client.py", line 465, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/regions.py", line 196, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/botocore/regions.py", line 230, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

**Comment by nsorros** [comment]
This has to do with AWS credentials to some extent. The way I have credentials setup the region is always defined. We could have the user pass this as an argument but I argue this is unnecessary and verbose. That said we can better document that this setup is required.

**Comment by ivyleavedtoadflax** [comment]
Did you need to install awscli and do `aws configure`? Did you need to add credentials?

**Comment by nsorros** [comment]
> Did you need to install awscli and do `aws configure`? Did you need to add credentials?

You can add credentials through aws configure or through environment variables. It’s basically whah boto looks for. https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html

This seems like we should improve documentation on this point.

**Comment by ivyleavedtoadflax** [comment]
This is always going to run on an instance, so it would be worth checking whether credentials need to be added at all. If we just gave the necessary permissions to the instance, would that be enough? If it is the case that we need to add credentials then we should create a new user with a limited permission scope for this.

**Comment by ivyleavedtoadflax** [comment]
Yes see https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials
The last place it checks is `Instance metadata service on an Amazon EC2 instance that has an IAM role configured.`. So the key here is just to configure a role with the necessary permissions, so that running `aws configure` is not required. It may be necessary to set a region somewhere still though

**Comment by nsorros** [comment]
> Yes see https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials
> The last place it checks is `Instance metadata service on an Amazon EC2 instance that has an IAM role configured.`. So the key here is just to configure a role with the necessary permissions, so that running `aws configure` is not required. It may be necessary to set a region somewhere still though

This seems a bit unrelated to the tool. I mean other than documentation on best practice. It’s up to the user to have credentials working somehow.

**Comment by ivyleavedtoadflax** [comment]
Agree, but it should go in the Readme.
